[[redirects]]
  from = "https://geode-solutions.netlify.com/*"
  to = "https://geode-solutions.com/:splat"
  status = 301
  force = true

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[context.production.environment]
  SITE_BRANCH = ""
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  SITE_URL = "https://geode-solutions.com"
[context.branch-deploy.environment]
  SITE_BRANCH = "/test"
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  SITE_URL = "https://next.geode-solutions.com"
[build]
  command = "rm -rf node_modules package-lock.json && npm i && npm run build"
  publish = "www"
