[[redirects]]
  from = "https://geode-solutions.netlify.com/*"
  to = "https://geode-solutions.com/:splat"
  status = 301
  force = true

[context.production.environment]
  SITE_BRANCH = ""
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
[context.branch-deploy.environment]
  SITE_BRANCH = "/test"
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
