[context.production.environment]
  SITE_BRANCH = ""
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  RECAPTCHA_SECRET_KEY = "6Lce72wgAAAAAH5B3DcQV2zpalP-7-kH51uUy461"
[context.deploy-preview.environment]
  SITE_BRANCH = ""
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  RECAPTCHA_SECRET_KEY = "6Lce72wgAAAAAH5B3DcQV2zpalP-7-kH51uUy461"
[context."next".environment]
  SITE_BRANCH = "/test"
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  RECAPTCHA_SECRET_KEY = "6Lce72wgAAAAAH5B3DcQV2zpalP-7-kH51uUy461"
