[[redirects]]
  from = "https://geode-solutions.netlify.com/*"
  to = "https://geode-solutions.com/:splat"
  status = 301
  force = true

[context.production.environment]
  SITE_BRANCH = ""
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  SITE_URL = "https://geode-solutions.com"
[context.deploy-preview.environment]
  SITE_BRANCH = ""
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  SITE_URL = "https://geode-solutions.com"
[context."next".environment]
  SITE_BRANCH = "/test"
  RECAPTCHA_SITE_KEY = "6Lce72wgAAAAAOXrHyDxRQBhk6NDTD80MrXOlgbC"
  SITE_URL = "https://next.geode-solutions.com"